name = "sextant"
version = "0.1.0"
description = "Type-safe JSON Schema generation and validation for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "Pevensie", repo = "sextant" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
youid = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
qcheck = ">= 1.0.2 and < 2.0.0"
